window.DATA = {
  "choosers": [
    { "id": "ben",    "name": "Ben",    "emoji": "🦕" },
    { "id": "baz",    "name": "Baz",    "emoji": "👶" },
    { "id": "willis", "name": "Willis", "emoji": "🦧" },
    { "id": "rick",   "name": "Rick",   "emoji": "🐦" },
    { "id": "harps",  "name": "Harpham","emoji": "👴🏻" },
    { "id": "gammy",  "name": "Gammy",  "emoji": "🦑" }
  ],
  "stocks": [
    { "ticker": "ABDP",    "name": "AB Dynamics PLC",                      "exchange": "LSE",    "chooser": "ben",    "quantity": 8,     "price": 11.2,    "currency": "GBP", "value": 89.60,   "cost": 214.75,  "change": -125.15, "changePct": -58.28, "todayPct": -0.36 },
    { "ticker": "AMD",     "name": "Advanced Micro Devices Inc",            "exchange": "NASDAQ", "chooser": "harps",  "quantity": 1,     "price": 515.05,  "currency": "USD", "value": 383.91,  "cost": 153.13,  "change": 230.78,  "changePct": 150.71, "todayPct": -5.04 },
    { "ticker": "ALB",     "name": "Albemarle Corp",                        "exchange": "NYSE",   "chooser": "willis", "quantity": 2,     "price": 165.66,  "currency": "USD", "value": 246.96,  "cost": 214.74,  "change": 32.22,   "changePct": 15.00,  "todayPct": -1.63 },
    { "ticker": "BKS",     "name": "Beeks Financial Cloud Group PLC",       "exchange": "LSE",    "chooser": "baz",    "quantity": 111,   "price": 1.55,    "currency": "GBP", "value": 172.05,  "cost": 287.72,  "change": -115.67, "changePct": -40.20, "todayPct": 0.00  },
    { "ticker": "BYND",    "name": "Beyond Meat Inc",                       "exchange": "NASDAQ", "chooser": "gammy",  "quantity": 2,     "price": 0.7837,  "currency": "USD", "value": 1.17,    "cost": 186.31,  "change": -185.14, "changePct": -99.37, "todayPct": 6.11  },
    { "ticker": "CNSL",    "name": "Cambridge Nutritional Sciences PLC",    "exchange": "LSE",    "chooser": "gammy",  "quantity": 475,   "price": 0.017,   "currency": "GBP", "value": 8.08,    "cost": 258.81,  "change": -250.73, "changePct": -96.88, "todayPct": -5.56 },
    { "ticker": "CKT",     "name": "Checkit PLC",                           "exchange": "LSE",    "chooser": "rick",   "quantity": 546,   "price": 0.24,    "currency": "GBP", "value": 131.04,  "cost": 291.14,  "change": -160.10, "changePct": -54.99, "todayPct": 0.00  },
    { "ticker": "CHRY",    "name": "Chrysalis Investments Limited",          "exchange": "LSE",    "chooser": "gammy","quantity": 381,   "price": 0.785,   "currency": "GBP", "value": 299.09,  "cost": 239.78,  "change": 59.31,   "changePct": 24.74,  "todayPct": 0.26  },
    { "ticker": "CRW",     "name": "Craneware PLC",                         "exchange": "LSE",    "chooser": "ben",    "quantity": 13,    "price": 15.28,   "currency": "GBP", "value": 198.64,  "cost": 228.34,  "change": -29.70,  "changePct": -13.01, "todayPct": 2.28  },
    { "ticker": "EARN",    "name": "EARNZ PLC",                             "exchange": "LSE",    "chooser": "willis", "quantity": 30,    "price": 0.04,    "currency": "GBP", "value": 1.20,    "cost": 247.38,  "change": -246.18, "changePct": -99.51, "todayPct": 0.00  },
    { "ticker": "EML",     "name": "Emmerson PLC",                          "exchange": "LSE",    "chooser": "gammy",  "quantity": 3189,  "price": 0.02,    "currency": "GBP", "value": 63.78,   "cost": 301.74,  "change": -237.96, "changePct": -78.86, "todayPct": 11.11 },
    { "ticker": "UKW",     "name": "Greencoat UK Wind",                     "exchange": "LSE",    "chooser": "baz",    "quantity": 163,   "price": 1.037,   "currency": "GBP", "value": 169.03,  "cost": 238.80,  "change": -69.77,  "changePct": -29.22, "todayPct": 0.68  },
    { "ticker": "GNC",     "name": "Greencore Group PLC",                   "exchange": "LSE",    "chooser": "gammy",  "quantity": 43,    "price": 1.927,   "currency": "GBP", "value": 82.86,   "cost": 82.15,   "change": 0.71,    "changePct": 0.86,   "todayPct": -0.72 },
    { "ticker": "HPOW",    "name": "H-Power PLC",                           "exchange": "LSE",    "chooser": "rick",   "quantity": 1652,  "price": 0.1456,  "currency": "GBP", "value": 240.53,  "cost": 259.96,  "change": -19.43,  "changePct": -7.47,  "todayPct": -6.91 },
    { "ticker": "HEI",     "name": "Heidelberg Materials AG",               "exchange": "XETRA",  "chooser": "baz",    "quantity": 1,     "price": 175.35,  "currency": "EUR", "value": 151.61,  "cost": 179.47,  "change": -27.86,  "changePct": -15.52, "todayPct": 0.00  },
    { "ticker": "HEMO",    "name": "Hemogenyx Pharmaceuticals PLC",         "exchange": "LSE",    "chooser": "rick",   "quantity": 32,    "price": 7.21,    "currency": "GBP", "value": 230.72,  "cost": 254.24,  "change": -23.52,  "changePct": -9.25,  "todayPct": 1.12  },
    { "ticker": "IPC",     "name": "International Paper Co",                "exchange": "LSE",    "chooser": "baz",    "quantity": 12,    "price": 25.35,   "currency": "GBP", "value": 304.20,  "cost": 307.99,  "change": -3.79,   "changePct": -1.23,  "todayPct": 2.01  },
    { "ticker": "ISRG",    "name": "Intuitive Surgical Inc",                "exchange": "NASDAQ", "chooser": "harps",  "quantity": 1,     "price": 418.76,  "currency": "USD", "value": 312.13,  "cost": 206.08,  "change": 106.05,  "changePct": 51.46,  "todayPct": 2.80  },
    { "ticker": "ITM",     "name": "ITM Power PLC",                         "exchange": "LSE",    "chooser": "rick",   "quantity": 329,   "price": 1.607,   "currency": "GBP", "value": 528.70,  "cost": 274.67,  "change": 254.03,  "changePct": 92.49,  "todayPct": -8.33 },
    { "ticker": "KMB",     "name": "Kimberly-Clark Corp",                   "exchange": "NASDAQ", "chooser": "harps",  "quantity": 1,     "price": 94.55,   "currency": "USD", "value": 70.48,   "cost": 81.34,   "change": -10.86,  "changePct": -13.36, "todayPct": -0.22 },
    { "ticker": "LFUS",    "name": "Littelfuse Inc",                        "exchange": "NASDAQ", "chooser": "harps",  "quantity": 1,     "price": 476.23,  "currency": "USD", "value": 354.97,  "cost": 204.52,  "change": 150.45,  "changePct": 73.56,  "todayPct": -1.75 },
    { "ticker": "LULU",    "name": "Lululemon Athletica Inc",               "exchange": "NASDAQ", "chooser": "ben",    "quantity": 1,     "price": 126.9,   "currency": "USD", "value": 94.59,   "cost": 222.24,  "change": -127.65, "changePct": -57.44, "todayPct": 0.68  },
    { "ticker": "NVDA",    "name": "NVIDIA Corp",                           "exchange": "NASDAQ", "chooser": "gammy",  "quantity": 2,     "price": 214.8,   "currency": "USD", "value": 320.21,  "cost": 201.44,  "change": 118.77,  "changePct": 58.96,  "todayPct": -0.05 },
    { "ticker": "ORSTED",  "name": "Orsted AS",                             "exchange": "XCSE",   "chooser": "willis", "quantity": 5,     "price": 166.9,   "currency": "DKK", "value": 96.52,   "cost": 126.69,  "change": -30.17,  "changePct": -23.81, "todayPct": 0.00  },
    { "ticker": "PLTR",    "name": "Palantir Technologies Inc",             "exchange": "NASDAQ", "chooser": "harps",  "quantity": 12,    "price": 142.46,  "currency": "USD", "value": 1274.24, "cost": 242.54,  "change": 1031.70, "changePct": 425.37, "todayPct": 0.18  },
    { "ticker": "PFE",     "name": "Pfizer Inc",                            "exchange": "NYSE",   "chooser": "gammy",  "quantity": 24,    "price": 25.76,   "currency": "USD", "value": 460.82,  "cost": 507.00,  "change": -46.18,  "changePct": -9.11,  "todayPct": 1.58  },
    { "ticker": "RNWH",    "name": "Renew Holdings PLC",                    "exchange": "LSE",    "chooser": "baz",    "quantity": 29,    "price": 8.71,    "currency": "GBP", "value": 252.59,  "cost": 239.03,  "change": 13.56,   "changePct": 5.67,   "todayPct": -0.57 },
    { "ticker": "RBRK",    "name": "Rubrik Inc Class A",                    "exchange": "NYSE",   "chooser": "rick",   "quantity": 4,     "price": 77.89,   "currency": "USD", "value": 232.23,  "cost": 253.74,  "change": -21.51,  "changePct": -8.48,  "todayPct": -2.00 },
    { "ticker": "BS08G23", "name": "SKILLZ INC",                            "exchange": "SEDOL",  "chooser": "ben",    "quantity": 10,    "price": 9.78,    "currency": "USD", "value": 72.90,   "cost": 265.06,  "change": -192.16, "changePct": -72.50, "todayPct": 0.00  },
    { "ticker": "SNOW",    "name": "Snowflake Inc",                         "exchange": "NYSE",   "chooser": "rick",   "quantity": 1,     "price": 252.51,  "currency": "USD", "value": 188.22,  "cost": 239.03,  "change": -50.81,  "changePct": -21.26, "todayPct": 4.70  },
    { "ticker": "SQM",     "name": "Sociedad Quimica Y Minera De Chile SA", "exchange": "NYSE",   "chooser": "rick",   "quantity": 15,    "price": 78.16,   "currency": "USD", "value": 873.88,  "cost": 444.25,  "change": 429.63,  "changePct": 96.71,  "todayPct": -0.53 },
    { "ticker": "SCT",     "name": "Softcat PLC",                           "exchange": "LSE",    "chooser": "willis", "quantity": 15,    "price": 18.79,   "currency": "GBP", "value": 281.85,  "cost": 241.88,  "change": 39.97,   "changePct": 16.52,  "todayPct": 1.79  },
    { "ticker": "SSE",     "name": "SSE PLC",                               "exchange": "LSE",    "chooser": "willis", "quantity": 13,    "price": 23.78,   "currency": "GBP", "value": 309.14,  "cost": 240.23,  "change": 68.91,   "changePct": 28.69,  "todayPct": 1.80  },
    { "ticker": "SLP",     "name": "Sylvania Platinum Ltd",                 "exchange": "LSE",    "chooser": "harps",  "quantity": 999,   "price": 0.93,    "currency": "GBP", "value": 929.07,  "cost": 483.94,  "change": 445.13,  "changePct": 91.98,  "todayPct": 1.09  },
    { "ticker": "TGTX",    "name": "TG Therapeutics Inc",                   "exchange": "NASDAQ", "chooser": "harps",  "quantity": 10,    "price": 41.93,   "currency": "USD", "value": 312.54,  "cost": 322.27,  "change": -9.73,   "changePct": -3.02,  "todayPct": 4.52  },
    { "ticker": "THX",     "name": "Thor Explorations Ltd",                 "exchange": "LSE",    "chooser": "baz",    "quantity": 181,   "price": 0.68,    "currency": "GBP", "value": 123.08,  "cost": 136.95,  "change": -13.87,  "changePct": -10.13, "todayPct": -1.45 },
    { "ticker": "PATH",    "name": "UiPath Inc Class A",                    "exchange": "NYSE",   "chooser": "ben",    "quantity": 35,    "price": 12.04,   "currency": "USD", "value": 314.10,  "cost": 299.79,  "change": 14.31,   "changePct": 4.77,   "todayPct": 3.17  },
    { "ticker": "BN4MYF5", "name": "Vestas Wind System",                   "exchange": "SEDOL",  "chooser": "willis", "quantity": 8,     "price": 178,     "currency": "DKK", "value": 164.71,  "cost": 224.64,  "change": -59.93,  "changePct": -26.68, "todayPct": 0.00  },
    { "ticker": "WBI",     "name": "Woodbois Ltd",                          "exchange": "LSE",    "chooser": "willis", "quantity": 10575, "price": 0.0003,  "currency": "GBP", "value": 3.17,    "cost": 252.86,  "change": -249.69, "changePct": -98.75, "todayPct": 0.00  },
    { "ticker": "YCA",     "name": "Yellow Cake PLC",                       "exchange": "LSE",    "chooser": "baz",    "quantity": 85,    "price": 5.595,   "currency": "GBP", "value": 475.58,  "cost": 437.27,  "change": 38.31,   "changePct": 8.76,   "todayPct": -2.36 },
    { "ticker": "ZNWD",    "name": "Zinnwald Lithium PLC",                  "exchange": "LSE",    "chooser": "harps",  "quantity": 2025,  "price": 0.085,   "currency": "GBP", "value": 172.13,  "cost": 259.92,  "change": -87.79,  "changePct": -33.78, "todayPct": 0.00  },
    { "ticker": "ZS",      "name": "Zscaler Inc",                           "exchange": "NASDAQ", "chooser": "baz",    "quantity": 2,     "price": 136.82,  "currency": "USD", "value": 203.97,  "cost": 236.74,  "change": -32.77,  "changePct": -13.84, "todayPct": 1.82  }
  ],
  "portfolio": {
    "totalValue": 11196.29,
    "totalCost": 10590.57,
    "totalChange": 605.72,
    "totalChangePct": 5.72,
    "cash": 24.85,
    "asOf": "2026-06-04"
  }
};
