window.DATA = {
  "choosers": [
    { "id": "ben",    "name": "Ben",    "emoji": "🦕" },
    { "id": "baz",    "name": "Baz",    "emoji": "👶" },
    { "id": "willis", "name": "Willis", "emoji": "🦧" },
    { "id": "rick",   "name": "Rick",   "emoji": "🐦" },
    { "id": "harps",  "name": "Harpham","emoji": "👴🏻" },
    { "id": "gammy",  "name": "Gammy",  "emoji": "🦑" }
  ],
  "stocks": [
    { "ticker": "ABDP",    "name": "AB Dynamics PLC",                      "exchange": "LSE",    "chooser": "ben",    "quantity": 8,     "price": 10.32,   "currency": "GBP", "value": 82.56,   "cost": 214.75,  "change": -132.19, "changePct": -61.56, "todayPct": 0.19  },
    { "ticker": "AMD",     "name": "Advanced Micro Devices Inc",            "exchange": "NASDAQ", "chooser": "harps",  "quantity": 1,     "price": 503.28,  "currency": "USD", "value": 374.78,  "cost": 153.13,  "change": 221.65,  "changePct": 144.75, "todayPct": 0.00  },
    { "ticker": "ALB",     "name": "Albemarle Corp",                        "exchange": "NYSE",   "chooser": "willis", "quantity": 2,     "price": 118.2,   "currency": "USD", "value": 176.04,  "cost": 214.74,  "change": -38.70,  "changePct": -18.02, "todayPct": -2.11 },
    { "ticker": "BKS",     "name": "Beeks Financial Cloud Group PLC",       "exchange": "LSE",    "chooser": "baz",    "quantity": 111,   "price": 1.9,     "currency": "GBP", "value": 210.90,  "cost": 287.72,  "change": -76.82,  "changePct": -26.70, "todayPct": 0.00  },
    { "ticker": "BYND",    "name": "Beyond Meat Inc",                       "exchange": "NASDAQ", "chooser": "gammy",  "quantity": 2,     "price": 0.5997,  "currency": "USD", "value": 0.89,    "cost": 186.31,  "change": -185.42, "changePct": -99.52, "todayPct": 0.00  },
    { "ticker": "CNSL",    "name": "Cambridge Nutritional Sciences PLC",    "exchange": "LSE",    "chooser": "gammy",  "quantity": 475,   "price": 0.016,   "currency": "GBP", "value": 7.60,    "cost": 258.81,  "change": -251.21, "changePct": -97.06, "todayPct": 0.00, "formerly": "Omega Diagnostics" },
    { "ticker": "CKT",     "name": "Checkit PLC",                           "exchange": "LSE",    "chooser": "rick",   "quantity": 546,   "price": 0.19,    "currency": "GBP", "value": 103.74,  "cost": 291.14,  "change": -187.40, "changePct": -64.37, "todayPct": 0.00  },
    { "ticker": "CHRY",    "name": "Chrysalis Investments Limited",          "exchange": "LSE",    "chooser": "gammy","quantity": 381,   "price": 0.756,   "currency": "GBP", "value": 288.04,  "cost": 239.78,  "change": 48.26,   "changePct": 20.13,  "todayPct": -0.13 },
    { "ticker": "CRW",     "name": "Craneware PLC",                         "exchange": "LSE",    "chooser": "ben",    "quantity": 13,    "price": 11.46,   "currency": "GBP", "value": 148.98,  "cost": 228.34,  "change": -79.36,  "changePct": -34.76, "todayPct": 0.70  },
    { "ticker": "EARN",    "name": "EARNZ PLC",                             "exchange": "LSE",    "chooser": "willis", "quantity": 30,    "price": 0.031,   "currency": "GBP", "value": 0.93,    "cost": 247.38,  "change": -246.45, "changePct": -99.62, "todayPct": 0.00, "formerly": "Verditek" },
    { "ticker": "EML",     "name": "Emmerson PLC",                          "exchange": "LSE",    "chooser": "gammy",  "quantity": 3189,  "price": 0.018,   "currency": "GBP", "value": 57.40,   "cost": 301.74,  "change": -244.34, "changePct": -80.98, "todayPct": 0.00  },
    { "ticker": "UKW",     "name": "Greencoat UK Wind",                     "exchange": "LSE",    "chooser": "baz",    "quantity": 163,   "price": 1.049,   "currency": "GBP", "value": 170.99,  "cost": 238.80,  "change": -67.81,  "changePct": -28.40, "todayPct": 0.29  },
    { "ticker": "GNC",     "name": "Greencore Group PLC",                   "exchange": "LSE",    "chooser": "gammy",  "quantity": 43,    "price": 2.126,   "currency": "GBP", "value": 91.42,   "cost": 82.15,   "change": 9.27,    "changePct": 11.28,  "todayPct": -0.84 },
    { "ticker": "HPOW",    "name": "H-Power PLC",                           "exchange": "LSE",    "chooser": "rick",   "quantity": 1652,  "price": 0.1082,  "currency": "GBP", "value": 178.75,  "cost": 259.96,  "change": -81.21,  "changePct": -31.24, "todayPct": 0.93, "formerly": "AFC Energy" },
    { "ticker": "HEI",     "name": "Heidelberg Materials AG",               "exchange": "XETRA",  "chooser": "baz",    "quantity": 1,     "price": 169.2,   "currency": "EUR", "value": 143.84,  "cost": 179.47,  "change": -35.63,  "changePct": -19.85, "todayPct": 0.00  },
    { "ticker": "HEMO",    "name": "Hemogenyx Pharmaceuticals PLC",         "exchange": "LSE",    "chooser": "rick",   "quantity": 32,    "price": 7.31,    "currency": "GBP", "value": 233.92,  "cost": 254.24,  "change": -20.32,  "changePct": -7.99,  "todayPct": -9.31 },
    { "ticker": "IPC",     "name": "International Paper Co",                "exchange": "LSE",    "chooser": "baz",    "quantity": 12,    "price": 27.05,   "currency": "GBP", "value": 324.60,  "cost": 307.99,  "change": 16.61,   "changePct": 5.39,   "todayPct": -0.92, "formerly": "DS Smith" },
    { "ticker": "ISRG",    "name": "Intuitive Surgical Inc",                "exchange": "NASDAQ", "chooser": "harps",  "quantity": 1,     "price": 353.01,  "currency": "USD", "value": 262.88,  "cost": 206.08,  "change": 56.80,   "changePct": 27.56,  "todayPct": 0.00  },
    { "ticker": "ITM",     "name": "ITM Power PLC",                         "exchange": "LSE",    "chooser": "rick",   "quantity": 329,   "price": 1.087,   "currency": "GBP", "value": 357.62,  "cost": 274.67,  "change": 82.95,   "changePct": 30.20,  "todayPct": 2.55  },
    { "ticker": "KMB",     "name": "Kimberly-Clark Corp",                   "exchange": "NASDAQ", "chooser": "harps",  "quantity": 1,     "price": 108.48,  "currency": "USD", "value": 80.78,   "cost": 81.34,   "change": -0.56,   "changePct": -0.69,  "todayPct": 0.14  },
    { "ticker": "KTOS",    "name": "Kratos Defense & Security Solutions Inc","exchange": "NASDAQ", "chooser": "ben",    "quantity": 7,     "price": 45.94,   "currency": "USD", "value": 239.47,  "cost": 249.44,  "change": -9.97,   "changePct": -4.00,  "todayPct": 0.00  },
    { "ticker": "LFUS",    "name": "Littelfuse Inc",                        "exchange": "NASDAQ", "chooser": "harps",  "quantity": 1,     "price": 401.6,   "currency": "USD", "value": 299.05,  "cost": 204.52,  "change": 94.53,   "changePct": 46.22,  "todayPct": 0.97  },
    { "ticker": "LULU",    "name": "Lululemon Athletica Inc",               "exchange": "NASDAQ", "chooser": "ben",    "quantity": 1,     "price": 116.67,  "currency": "USD", "value": 86.88,   "cost": 222.24,  "change": -135.36, "changePct": -60.91, "todayPct": 0.00  },
    { "ticker": "NVDA",    "name": "NVIDIA Corp",                           "exchange": "NASDAQ", "chooser": "gammy",  "quantity": 2,     "price": 203.32,  "currency": "USD", "value": 302.81,  "cost": 201.44,  "change": 101.37,  "changePct": 50.32,  "todayPct": 0.00  },
    { "ticker": "ORSTED",  "name": "Orsted AS",                             "exchange": "XCSE",   "chooser": "willis", "quantity": 5,     "price": 151.6,   "currency": "DKK", "value": 86.17,   "cost": 126.69,  "change": -40.52,  "changePct": -31.98, "todayPct": 0.00  },
    { "ticker": "PLTR",    "name": "Palantir Technologies Inc",             "exchange": "NASDAQ", "chooser": "harps",  "quantity": 12,    "price": 134.85,  "currency": "USD", "value": 1205.02, "cost": 242.54,  "change": 962.48,  "changePct": 396.83, "todayPct": 0.00  },
    { "ticker": "PFE",     "name": "Pfizer Inc",                            "exchange": "NYSE",   "chooser": "gammy",  "quantity": 24,    "price": 24.74,   "currency": "USD", "value": 442.15,  "cost": 507.00,  "change": -64.85,  "changePct": -12.79, "todayPct": 0.00  },
    { "ticker": "RNWH",    "name": "Renew Holdings PLC",                    "exchange": "LSE",    "chooser": "baz",    "quantity": 29,    "price": 9.25,    "currency": "GBP", "value": 268.25,  "cost": 239.03,  "change": 29.22,   "changePct": 12.22,  "todayPct": 0.33  },
    { "ticker": "RBRK",    "name": "Rubrik Inc Class A",                    "exchange": "NYSE",   "chooser": "rick",   "quantity": 4,     "price": 78.2,    "currency": "USD", "value": 232.93,  "cost": 253.74,  "change": -20.81,  "changePct": -8.20,  "todayPct": 0.00  },
    { "ticker": "BS08G23", "name": "FIRY Inc",                              "exchange": "SEDOL",  "chooser": "ben",    "quantity": 10,    "price": 8.61,    "currency": "USD", "value": 64.12,   "cost": 265.06,  "change": -200.94, "changePct": -75.81, "todayPct": 0.00, "formerly": "Skillz" },
    { "ticker": "SNOW",    "name": "Snowflake Inc",                         "exchange": "NYSE",   "chooser": "rick",   "quantity": 1,     "price": 274.31,  "currency": "USD", "value": 204.27,  "cost": 239.03,  "change": -34.76,  "changePct": -14.54, "todayPct": 0.00  },
    { "ticker": "SQM",     "name": "Sociedad Quimica Y Minera De Chile SA", "exchange": "NYSE",   "chooser": "rick",   "quantity": 15,    "price": 67.68,   "currency": "USD", "value": 755.98,  "cost": 444.25,  "change": 311.73,  "changePct": 70.17,  "todayPct": -3.09 },
    { "ticker": "SCT",     "name": "Softcat PLC",                           "exchange": "LSE",    "chooser": "willis", "quantity": 15,    "price": 18.55,   "currency": "GBP", "value": 278.25,  "cost": 241.88,  "change": 36.37,   "changePct": 15.04,  "todayPct": -0.70 },
    { "ticker": "SSE",     "name": "SSE PLC",                               "exchange": "LSE",    "chooser": "willis", "quantity": 13,    "price": 24.56,   "currency": "GBP", "value": 319.28,  "cost": 240.23,  "change": 79.05,   "changePct": 32.91,  "todayPct": -0.12 },
    { "ticker": "SLP",     "name": "Sylvania Platinum Ltd",                 "exchange": "LSE",    "chooser": "harps",  "quantity": 999,   "price": 0.85,    "currency": "GBP", "value": 849.15,  "cost": 483.94,  "change": 365.21,  "changePct": 75.47,  "todayPct": 1.19  },
    { "ticker": "TGTX",    "name": "TG Therapeutics Inc",                   "exchange": "NASDAQ", "chooser": "harps",  "quantity": 10,    "price": 53.95,   "currency": "USD", "value": 401.74,  "cost": 322.27,  "change": 79.47,   "changePct": 24.66,  "todayPct": -1.61 },
    { "ticker": "THX",     "name": "Thor Explorations Ltd",                 "exchange": "LSE",    "chooser": "baz",    "quantity": 181,   "price": 0.56,    "currency": "GBP", "value": 101.36,  "cost": 136.95,  "change": -35.59,  "changePct": -25.99, "todayPct": 0.00  },
    { "ticker": "PATH",    "name": "UiPath Inc Class A",                    "exchange": "NYSE",   "chooser": "ben",    "quantity": 35,    "price": 12.16,   "currency": "USD", "value": 316.93,  "cost": 299.79,  "change": 17.14,   "changePct": 5.72,   "todayPct": 0.00  },
    { "ticker": "BN4MYF5", "name": "Vestas Wind System",                   "exchange": "SEDOL",  "chooser": "willis", "quantity": 8,     "price": 180.8,   "currency": "DKK", "value": 164.43,  "cost": 224.64,  "change": -60.21,  "changePct": -26.80, "todayPct": 0.00  },
    { "ticker": "WBI",     "name": "Woodbois Ltd",                          "exchange": "LSE",    "chooser": "willis", "quantity": 10575, "price": 0.0003,  "currency": "GBP", "value": 3.17,    "cost": 252.86,  "change": -249.69, "changePct": -98.75, "todayPct": 0.00  },
    { "ticker": "YCA",     "name": "Yellow Cake PLC",                       "exchange": "LSE",    "chooser": "baz",    "quantity": 85,    "price": 5.225,   "currency": "GBP", "value": 444.13,  "cost": 437.27,  "change": 6.86,    "changePct": 1.57,   "todayPct": -0.67 },
    { "ticker": "ZNWD",    "name": "Zinnwald Lithium PLC",                  "exchange": "LSE",    "chooser": "harps",  "quantity": 2025,  "price": 0.085,   "currency": "GBP", "value": 172.13,  "cost": 259.92,  "change": -87.79,  "changePct": -33.78, "todayPct": 0.00  },
    { "ticker": "ZS",      "name": "Zscaler Inc",                           "exchange": "NASDAQ", "chooser": "baz",    "quantity": 2,     "price": 149.78,  "currency": "USD", "value": 223.07,  "cost": 236.74,  "change": -13.67,  "changePct": -5.77,  "todayPct": 0.00  }
  ],
  "exited": [
    { "ticker": "CHPT", "name": "ChargePoint Holdings Inc", "chooser": "ben" },
    { "ticker": "EMIS", "name": "EMIS Group PLC",           "chooser": "willis" }
  ],
  "previous": {
    "asOf": "2026-06-04",
    "portfolio": { "totalValue": 11196.29, "totalChangePct": 5.72 },
    "stocks": [
      { "ticker": "ABDP", "chooser": "ben",    "changePct": -58.28 },
      { "ticker": "AMD",  "chooser": "harps",  "changePct": 150.71 },
      { "ticker": "ALB",  "chooser": "willis", "changePct": 15.00 },
      { "ticker": "BKS",  "chooser": "baz",    "changePct": -40.20 },
      { "ticker": "BYND", "chooser": "gammy",  "changePct": -99.37 },
      { "ticker": "CNSL", "chooser": "gammy",  "changePct": -96.88 },
      { "ticker": "CKT",  "chooser": "rick",   "changePct": -54.99 },
      { "ticker": "CHRY", "chooser": "gammy",  "changePct": 24.74 },
      { "ticker": "CRW",  "chooser": "ben",    "changePct": -13.01 },
      { "ticker": "EARN", "chooser": "willis", "changePct": -99.51 },
      { "ticker": "EML",  "chooser": "gammy",  "changePct": -78.86 },
      { "ticker": "UKW",  "chooser": "baz",    "changePct": -29.22 },
      { "ticker": "GNC",  "chooser": "gammy",  "changePct": 0.86 },
      { "ticker": "HPOW", "chooser": "rick",   "changePct": -7.47 },
      { "ticker": "HEI",  "chooser": "baz",    "changePct": -15.52 },
      { "ticker": "HEMO", "chooser": "rick",   "changePct": -9.25 },
      { "ticker": "IPC",  "chooser": "baz",    "changePct": -1.23 },
      { "ticker": "ISRG", "chooser": "harps",  "changePct": 51.46 },
      { "ticker": "ITM",  "chooser": "rick",   "changePct": 92.49 },
      { "ticker": "KMB",  "chooser": "harps",  "changePct": -13.36 },
      { "ticker": "LFUS", "chooser": "harps",  "changePct": 73.56 },
      { "ticker": "LULU", "chooser": "ben",    "changePct": -57.44 },
      { "ticker": "NVDA", "chooser": "gammy",  "changePct": 58.96 },
      { "ticker": "ORSTED","chooser": "willis","changePct": -23.81 },
      { "ticker": "PLTR", "chooser": "harps",  "changePct": 425.37 },
      { "ticker": "PFE",  "chooser": "gammy",  "changePct": -9.11 },
      { "ticker": "RNWH", "chooser": "baz",    "changePct": 5.67 },
      { "ticker": "RBRK", "chooser": "rick",   "changePct": -8.48 },
      { "ticker": "BS08G23","chooser": "ben",  "changePct": -72.50 },
      { "ticker": "SNOW", "chooser": "rick",   "changePct": -21.26 },
      { "ticker": "SQM",  "chooser": "rick",   "changePct": 96.71 },
      { "ticker": "SCT",  "chooser": "willis", "changePct": 16.52 },
      { "ticker": "SSE",  "chooser": "willis", "changePct": 28.69 },
      { "ticker": "SLP",  "chooser": "harps",  "changePct": 91.98 },
      { "ticker": "TGTX", "chooser": "harps",  "changePct": -3.02 },
      { "ticker": "THX",  "chooser": "baz",    "changePct": -10.13 },
      { "ticker": "PATH", "chooser": "ben",    "changePct": 4.77 },
      { "ticker": "BN4MYF5","chooser": "willis","changePct": -26.68 },
      { "ticker": "WBI",  "chooser": "willis", "changePct": -98.75 },
      { "ticker": "YCA",  "chooser": "baz",    "changePct": 8.76 },
      { "ticker": "ZNWD", "chooser": "harps",  "changePct": -33.78 },
      { "ticker": "ZS",   "chooser": "baz",    "changePct": -13.84 }
    ]
  },
  "portfolio": {
    "totalValue": 10757.40,
    "totalCost": 10840.01,
    "totalChange": -82.61,
    "totalChangePct": -0.76,
    "cash": 21.45,
    "asOf": "2026-07-21"
  }
};
