window.DATA = {
  "choosers": [
    { "id": "ben",    "name": "Ben",    "emoji": "🦕" },
    { "id": "baz",    "name": "Baz",    "emoji": "👶" },
    { "id": "willis", "name": "Willis", "emoji": "🦧" },
    { "id": "rick",   "name": "Rick",   "emoji": "🐦" },
    { "id": "harps",  "name": "Harpham","emoji": "👴🏻" },
    { "id": "gammy",  "name": "Gammy",  "emoji": "🦑" }
  ],
  "stocks": [
    { "ticker": "ABDP",    "name": "AB Dynamics PLC",                      "exchange": "LSE",      "chooser": "ben",    "quantity": 8,     "price": 8.22,    "currency": "GBP", "value": 65.76,   "cost": 214.75,  "change": -148.99, "changePct": -69.38, "todayPct": -0.12 },
    { "ticker": "AMD",     "name": "Advanced Micro Devices Inc",            "exchange": "NASDAQ",   "chooser": "harps",  "quantity": 1,     "price": 502.97,  "currency": "USD", "value": 372.63,  "cost": 153.13,  "change": 219.50,  "changePct": 143.34, "todayPct": 1.91  },
    { "ticker": "ALB",     "name": "Albemarle Corp",                        "exchange": "NYSE",     "chooser": "willis", "quantity": 2,     "price": 113.38,  "currency": "USD", "value": 168.00,  "cost": 214.74,  "change": -46.74,  "changePct": -21.77, "todayPct": -1.43 },
    { "ticker": "AMG",     "name": "AMG Critical Materials NV",             "exchange": "EURONEXT", "chooser": "harps",  "quantity": 3,     "price": 29.16,   "currency": "EUR", "value": 74.86,   "cost": 111.38,  "change": -36.52,  "changePct": -32.79, "todayPct": 0.00, "formerly": "Zinnwald Lithium" },
    { "ticker": "BKS",     "name": "Beeks Financial Cloud Group PLC",       "exchange": "LSE",      "chooser": "baz",    "quantity": 111,   "price": 2.25,    "currency": "GBP", "value": 249.75,  "cost": 287.72,  "change": -37.97,  "changePct": -13.20, "todayPct": 2.27  },
    { "ticker": "BYND",    "name": "Beyond Meat Inc",                       "exchange": "NASDAQ",   "chooser": "gammy",  "quantity": 2,     "price": 0.5997,  "currency": "USD", "value": 0.89,    "cost": 186.31,  "change": -185.42, "changePct": -99.52, "todayPct": 0.00  },
    { "ticker": "CNSL",    "name": "Cambridge Nutritional Sciences PLC",    "exchange": "LSE",      "chooser": "gammy",  "quantity": 475,   "price": 0.014,   "currency": "GBP", "value": 6.65,    "cost": 258.81,  "change": -252.16, "changePct": -97.43, "todayPct": 7.69, "formerly": "Omega Diagnostics" },
    { "ticker": "CKT",     "name": "Checkit PLC",                           "exchange": "LSE",      "chooser": "rick",   "quantity": 546,   "price": 0.235,   "currency": "GBP", "value": 128.31,  "cost": 291.14,  "change": -162.83, "changePct": -55.93, "todayPct": 2.17  },
    { "ticker": "CHRY",    "name": "Chrysalis Investments Limited",          "exchange": "LSE",      "chooser": "gammy",  "quantity": 381,   "price": 0.67,    "currency": "GBP", "value": 255.27,  "cost": 239.78,  "change": 15.49,   "changePct": 6.46,   "todayPct": -1.90 },
    { "ticker": "CRW",     "name": "Craneware PLC",                         "exchange": "LSE",      "chooser": "ben",    "quantity": 13,    "price": 12.9,    "currency": "GBP", "value": 167.70,  "cost": 228.34,  "change": -60.64,  "changePct": -26.56, "todayPct": -1.07 },
    { "ticker": "EARN",    "name": "EARNZ PLC",                             "exchange": "LSE",      "chooser": "willis", "quantity": 30,    "price": 0.0425,  "currency": "GBP", "value": 1.28,    "cost": 247.38,  "change": -246.10, "changePct": -99.48, "todayPct": 1.19, "formerly": "Verditek" },
    { "ticker": "EML",     "name": "Emmerson PLC",                          "exchange": "LSE",      "chooser": "gammy",  "quantity": 3189,  "price": 0.015,   "currency": "GBP", "value": 47.84,   "cost": 301.74,  "change": -253.90, "changePct": -84.15, "todayPct": 0.00  },
    { "ticker": "FTC",     "name": "Filtronic PLC",                         "exchange": "LSE",      "chooser": "baz",    "quantity": 172,   "price": 2.15,    "currency": "GBP", "value": 369.80,  "cost": 378.24,  "change": -8.44,   "changePct": -2.23,  "todayPct": -8.51 },
    { "ticker": "UKW",     "name": "Greencoat UK Wind",                     "exchange": "LSE",      "chooser": "baz",    "quantity": 163,   "price": 1.118,   "currency": "GBP", "value": 182.23,  "cost": 238.80,  "change": -56.57,  "changePct": -23.69, "todayPct": 0.45  },
    { "ticker": "GNC",     "name": "Greencore Group PLC",                   "exchange": "LSE",      "chooser": "gammy",  "quantity": 43,    "price": 2.498,   "currency": "GBP", "value": 107.41,  "cost": 82.15,   "change": 25.26,   "changePct": 30.75,  "todayPct": -0.32 },
    { "ticker": "HPOW",    "name": "H-Power PLC",                           "exchange": "LSE",      "chooser": "rick",   "quantity": 1652,  "price": 0.0974,  "currency": "GBP", "value": 160.90,  "cost": 259.96,  "change": -99.06,  "changePct": -38.11, "todayPct": -3.37, "formerly": "AFC Energy" },
    { "ticker": "HEI",     "name": "Heidelberg Materials AG",               "exchange": "XETRA",    "chooser": "baz",    "quantity": 1,     "price": 150.1,   "currency": "EUR", "value": 128.44,  "cost": 179.47,  "change": -51.03,  "changePct": -28.43, "todayPct": 0.00  },
    { "ticker": "HEMO",    "name": "Hemogenyx Pharmaceuticals PLC",         "exchange": "LSE",      "chooser": "rick",   "quantity": 32,    "price": 4.445,   "currency": "GBP", "value": 142.24,  "cost": 254.24,  "change": -112.00, "changePct": -44.05, "todayPct": -1.88 },
    { "ticker": "IPC",     "name": "International Paper Co",                "exchange": "LSE",      "chooser": "baz",    "quantity": 12,    "price": 25.4,    "currency": "GBP", "value": 304.80,  "cost": 307.99,  "change": -3.19,   "changePct": -1.04,  "todayPct": -0.59, "formerly": "DS Smith" },
    { "ticker": "ISRG",    "name": "Intuitive Surgical Inc",                "exchange": "NASDAQ",   "chooser": "harps",  "quantity": 1,     "price": 377.89,  "currency": "USD", "value": 279.96,  "cost": 206.08,  "change": 73.88,   "changePct": 35.85,  "todayPct": -0.01 },
    { "ticker": "ITM",     "name": "ITM Power PLC",                         "exchange": "LSE",      "chooser": "rick",   "quantity": 329,   "price": 0.979,   "currency": "GBP", "value": 322.09,  "cost": 274.67,  "change": 47.42,   "changePct": 17.26,  "todayPct": -1.21 },
    { "ticker": "KMB",     "name": "Kimberly-Clark Corp",                   "exchange": "NASDAQ",   "chooser": "harps",  "quantity": 1,     "price": 97.59,   "currency": "USD", "value": 72.30,   "cost": 81.34,   "change": -9.04,   "changePct": -11.11, "todayPct": -1.49 },
    { "ticker": "KTOS",    "name": "Kratos Defense & Security Solutions Inc","exchange": "NASDAQ",  "chooser": "ben",    "quantity": 7,     "price": 48.23,   "currency": "USD", "value": 250.12,  "cost": 249.44,  "change": 0.68,    "changePct": 0.27,   "todayPct": 1.32  },
    { "ticker": "LFUS",    "name": "Littelfuse Inc",                        "exchange": "NASDAQ",   "chooser": "harps",  "quantity": 1,     "price": 394.2,   "currency": "USD", "value": 292.04,  "cost": 204.52,  "change": 87.52,   "changePct": 42.79,  "todayPct": -0.44 },
    { "ticker": "LULU",    "name": "Lululemon Athletica Inc",               "exchange": "NASDAQ",   "chooser": "ben",    "quantity": 1,     "price": 97.385,  "currency": "USD", "value": 72.15,   "cost": 222.24,  "change": -150.09, "changePct": -67.54, "todayPct": -2.91 },
    { "ticker": "NVDA",    "name": "NVIDIA Corp",                           "exchange": "NASDAQ",   "chooser": "gammy",  "quantity": 2,     "price": 211.91,  "currency": "USD", "value": 313.99,  "cost": 201.44,  "change": 112.55,  "changePct": 55.87,  "todayPct": 0.48  },
    { "ticker": "ORSTED",  "name": "Orsted AS",                             "exchange": "XCSE",     "chooser": "willis", "quantity": 5,     "price": 130.4,   "currency": "DKK", "value": 74.61,   "cost": 126.69,  "change": -52.08,  "changePct": -41.11, "todayPct": 0.00  },
    { "ticker": "PLTR",    "name": "Palantir Technologies Inc",             "exchange": "NASDAQ",   "chooser": "harps",  "quantity": 12,    "price": 174.62,  "currency": "USD", "value": 1552.41, "cost": 242.54,  "change": 1309.87, "changePct": 540.06, "todayPct": 0.75  },
    { "ticker": "PFE",     "name": "Pfizer Inc",                            "exchange": "NYSE",     "chooser": "gammy",  "quantity": 24,    "price": 27.535,  "currency": "USD", "value": 489.58,  "cost": 507.00,  "change": -17.42,  "changePct": -3.44,  "todayPct": -0.72 },
    { "ticker": "RNWH",    "name": "Renew Holdings PLC",                    "exchange": "LSE",      "chooser": "baz",    "quantity": 29,    "price": 8.56,    "currency": "GBP", "value": 248.24,  "cost": 239.03,  "change": 9.21,    "changePct": 3.85,   "todayPct": -1.50 },
    { "ticker": "RBRK",    "name": "Rubrik Inc Class A",                    "exchange": "NYSE",     "chooser": "rick",   "quantity": 4,     "price": 100.58,  "currency": "USD", "value": 298.06,  "cost": 253.74,  "change": 44.32,   "changePct": 17.47,  "todayPct": 0.35  },
    { "ticker": "BS08G23", "name": "FIRY Inc",                              "exchange": "SEDOL",    "chooser": "ben",    "quantity": 10,    "price": 10.26,   "currency": "USD", "value": 76.01,   "cost": 265.06,  "change": -189.05, "changePct": -71.32, "todayPct": 0.00, "formerly": "Skillz" },
    { "ticker": "SNOW",    "name": "Snowflake Inc",                         "exchange": "NYSE",     "chooser": "rick",   "quantity": 1,     "price": 327.39,  "currency": "USD", "value": 242.55,  "cost": 239.03,  "change": 3.52,    "changePct": 1.47,   "todayPct": -1.41 },
    { "ticker": "SQM",     "name": "Sociedad Quimica Y Minera De Chile SA", "exchange": "NYSE",     "chooser": "rick",   "quantity": 15,    "price": 69.4,    "currency": "USD", "value": 771.23,  "cost": 444.25,  "change": 326.98,  "changePct": 73.60,  "todayPct": -0.50 },
    { "ticker": "SCT",     "name": "Softcat PLC",                           "exchange": "LSE",      "chooser": "willis", "quantity": 15,    "price": 18.91,   "currency": "GBP", "value": 283.65,  "cost": 241.88,  "change": 41.77,   "changePct": 17.27,  "todayPct": 1.72  },
    { "ticker": "SSE",     "name": "SSE PLC",                               "exchange": "LSE",      "chooser": "willis", "quantity": 13,    "price": 23.33,   "currency": "GBP", "value": 303.29,  "cost": 240.23,  "change": 63.06,   "changePct": 26.25,  "todayPct": 0.95  },
    { "ticker": "SLP",     "name": "Sylvania Platinum Ltd",                 "exchange": "LSE",      "chooser": "harps",  "quantity": 999,   "price": 0.9,     "currency": "GBP", "value": 899.10,  "cost": 483.94,  "change": 415.16,  "changePct": 85.79,  "todayPct": 5.88  },
    { "ticker": "TGTX",    "name": "TG Therapeutics Inc",                   "exchange": "NASDAQ",   "chooser": "harps",  "quantity": 10,    "price": 53.4,    "currency": "USD", "value": 395.61,  "cost": 322.27,  "change": 73.34,   "changePct": 22.76,  "todayPct": -1.22 },
    { "ticker": "THX",     "name": "Thor Explorations Ltd",                 "exchange": "LSE",      "chooser": "baz",    "quantity": 181,   "price": 0.67,    "currency": "GBP", "value": 121.27,  "cost": 136.95,  "change": -15.68,  "changePct": -11.45, "todayPct": 1.52  },
    { "ticker": "PATH",    "name": "UiPath Inc Class A",                    "exchange": "NYSE",     "chooser": "ben",    "quantity": 35,    "price": 14.6,    "currency": "USD", "value": 378.57,  "cost": 299.79,  "change": 78.78,   "changePct": 26.28,  "todayPct": -0.41 },
    { "ticker": "BN4MYF5", "name": "Vestas Wind System",                   "exchange": "SEDOL",    "chooser": "willis", "quantity": 8,     "price": 205.7,   "currency": "DKK", "value": 188.31,  "cost": 224.64,  "change": -36.33,  "changePct": -16.17, "todayPct": 0.00  },
    { "ticker": "WBI",     "name": "Woodbois Ltd",                          "exchange": "LSE",      "chooser": "willis", "quantity": 10575, "price": 0.0003,  "currency": "GBP", "value": 3.17,    "cost": 252.86,  "change": -249.69, "changePct": -98.75, "todayPct": 0.00  },
    { "ticker": "YCA",     "name": "Yellow Cake PLC",                       "exchange": "LSE",      "chooser": "baz",    "quantity": 85,    "price": 5.595,   "currency": "GBP", "value": 475.58,  "cost": 437.27,  "change": 38.31,   "changePct": 8.76,   "todayPct": 2.85  },
    { "ticker": "ZS",      "name": "Zscaler Inc",                           "exchange": "NASDAQ",   "chooser": "baz",    "quantity": 2,     "price": 194.39,  "currency": "USD", "value": 288.03,  "cost": 236.74,  "change": 51.29,   "changePct": 21.66,  "todayPct": 1.45  }
  ],
  "exited": [
    { "ticker": "CHPT", "name": "ChargePoint Holdings Inc", "chooser": "ben" },
    { "ticker": "EMIS", "name": "EMIS Group PLC",           "chooser": "willis" }
  ],
  "previous": {
    "asOf": "2026-07-21",
    "portfolio": { "totalValue": 10757.40, "totalChangePct": -0.76 },
    "stocks": [
      { "ticker": "ABDP", "chooser": "ben",    "changePct": -61.56 },
      { "ticker": "AMD",  "chooser": "harps",  "changePct": 144.75 },
      { "ticker": "ALB",  "chooser": "willis", "changePct": -18.02 },
      { "ticker": "BKS",  "chooser": "baz",    "changePct": -26.70 },
      { "ticker": "BYND", "chooser": "gammy",  "changePct": -99.52 },
      { "ticker": "CNSL", "chooser": "gammy",  "changePct": -97.06 },
      { "ticker": "CKT",  "chooser": "rick",   "changePct": -64.37 },
      { "ticker": "CHRY", "chooser": "gammy",  "changePct": 20.13 },
      { "ticker": "CRW",  "chooser": "ben",    "changePct": -34.76 },
      { "ticker": "EARN", "chooser": "willis", "changePct": -99.62 },
      { "ticker": "EML",  "chooser": "gammy",  "changePct": -80.98 },
      { "ticker": "UKW",  "chooser": "baz",    "changePct": -28.40 },
      { "ticker": "GNC",  "chooser": "gammy",  "changePct": 11.28 },
      { "ticker": "HPOW", "chooser": "rick",   "changePct": -31.24 },
      { "ticker": "HEI",  "chooser": "baz",    "changePct": -19.85 },
      { "ticker": "HEMO", "chooser": "rick",   "changePct": -7.99 },
      { "ticker": "IPC",  "chooser": "baz",    "changePct": 5.39 },
      { "ticker": "ISRG", "chooser": "harps",  "changePct": 27.56 },
      { "ticker": "ITM",  "chooser": "rick",   "changePct": 30.20 },
      { "ticker": "KMB",  "chooser": "harps",  "changePct": -0.69 },
      { "ticker": "KTOS", "chooser": "ben",    "changePct": -4.00 },
      { "ticker": "LFUS", "chooser": "harps",  "changePct": 46.22 },
      { "ticker": "LULU", "chooser": "ben",    "changePct": -60.91 },
      { "ticker": "NVDA", "chooser": "gammy",  "changePct": 50.32 },
      { "ticker": "ORSTED","chooser": "willis","changePct": -31.98 },
      { "ticker": "PLTR", "chooser": "harps",  "changePct": 396.83 },
      { "ticker": "PFE",  "chooser": "gammy",  "changePct": -12.79 },
      { "ticker": "RNWH", "chooser": "baz",    "changePct": 12.22 },
      { "ticker": "RBRK", "chooser": "rick",   "changePct": -8.20 },
      { "ticker": "BS08G23","chooser": "ben",  "changePct": -75.81 },
      { "ticker": "SNOW", "chooser": "rick",   "changePct": -14.54 },
      { "ticker": "SQM",  "chooser": "rick",   "changePct": 70.17 },
      { "ticker": "SCT",  "chooser": "willis", "changePct": 15.04 },
      { "ticker": "SSE",  "chooser": "willis", "changePct": 32.91 },
      { "ticker": "SLP",  "chooser": "harps",  "changePct": 75.47 },
      { "ticker": "TGTX", "chooser": "harps",  "changePct": 24.66 },
      { "ticker": "THX",  "chooser": "baz",    "changePct": -25.99 },
      { "ticker": "PATH", "chooser": "ben",    "changePct": 5.72 },
      { "ticker": "BN4MYF5","chooser": "willis","changePct": -26.80 },
      { "ticker": "WBI",  "chooser": "willis", "changePct": -98.75 },
      { "ticker": "YCA",  "chooser": "baz",    "changePct": 1.57 },
      { "ticker": "ZNWD", "chooser": "harps",  "changePct": -33.78 },
      { "ticker": "ZS",   "chooser": "baz",    "changePct": -5.77 }
    ]
  },
  "portfolio": {
    "totalValue": 11625.79,
    "totalCost": 10883.40,
    "totalChange": 742.38,
    "totalChangePct": 6.82,
    "cash": 1.96,
    "asOf": "2026-09-15"
  }
};
